package it.diunito.pepper.data.services

import android.util.Log
import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.plugins.timeout
import io.ktor.client.request.header
import io.ktor.client.request.post
import io.ktor.client.request.setBody
import io.ktor.client.statement.HttpResponse
import io.ktor.http.ContentType
import io.ktor.http.contentType
import it.diunito.pepper.data.requests.LlmChatRequest
import it.diunito.pepper.data.requests.LlmMessage
import it.diunito.pepper.data.responses.LlmChatResponse

class LlmApiService(
    private val client: HttpClient,
    private val endpoint: String,
    private val apiKey: String
) {

    companion object {
        private const val TAG = "LlmApiService"
        private const val TIMEOUT_MS = 300_000L  // 5 minutes timeout for large remote models on HPC cluster

        private const val SYSTEM_PROMPT =
            "Sei Pepper, un robot assistente sociale dell'Università di Torino. " +
            "Rispondi in modo cordiale, conciso e utile. " +
            "Puoi rispondere in italiano e in inglese in base alla lingua dell'utente."
    }

    private val conversationHistory = mutableListOf<LlmMessage>(
        LlmMessage(role = "system", content = SYSTEM_PROMPT)
    )

    /**
     * Send a user message and get the assistant's reply.
     * Maintains conversation history for multi-turn context.
     */
    suspend fun chat(userMessage: String, modelId: String): String {
        conversationHistory.add(LlmMessage(role = "user", content = userMessage))

        val request = LlmChatRequest(
            model = modelId,
            messages = conversationHistory.toList()
        )

        return try {
            val response: HttpResponse = client.post("$endpoint/chat/completions") {
                contentType(ContentType.Application.Json)
                header("Authorization", "Bearer $apiKey")
                setBody(request)
                timeout {
                    requestTimeoutMillis = TIMEOUT_MS
                    connectTimeoutMillis = 15_000
                    socketTimeoutMillis = TIMEOUT_MS
                }
            }

            if (response.status.value in 200..299) {
                val chatResponse = response.body<LlmChatResponse>()
                val assistantMessage = chatResponse.choices.firstOrNull()?.message?.content
                    ?: "Nessuna risposta dal modello."

                // Remove <think> tags generated by reasoning models (e.g., DeepSeek)
                val cleanedMessage = assistantMessage
                    .replace(Regex("<think>[\\s\\S]*?</think>"), "")
                    .trim()

                conversationHistory.add(LlmMessage(role = "assistant", content = cleanedMessage))
                Log.d(TAG, "LLM response received (model=$modelId, history=${conversationHistory.size} msgs)")
                cleanedMessage
            } else {
                Log.e(TAG, "LLM API error: HTTP ${response.status.value}")
                // Remove the failed user message from history to maintain context consistency
                conversationHistory.removeLastOrNull()
                throw LlmHttpException(response.status.value, "Errore nella comunicazione con il modello (HTTP ${response.status.value}).")
            }
        } catch (e: Exception) {
            Log.e(TAG, "LLM API call failed", e)
            // Remove the failed user message from history to maintain context consistency
            conversationHistory.removeLastOrNull()
            throw e
        }
    }

    /**
     * Reset the conversation history, keeping only the system prompt.
     */
    fun resetConversation() {
        conversationHistory.clear()
        conversationHistory.add(LlmMessage(role = "system", content = SYSTEM_PROMPT))
        Log.d(TAG, "Conversation history reset")
    }
}

class LlmHttpException(val statusCode: Int, message: String) : Exception(message)
